export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE_API = "GET_PROFILE_API";
export const GET_PROFILE_API_SUCCEED = "GET_PROFILE_API_SUCCEED";
export const GET_PROFILE_API_FAIL = "GET_PROFILE_API_FAIL";

export const CHANGE_PASS_API = "CHANGE_PASS_API";
export const CHANGE_PASS_API_SUCCEED = "CHANGE_PASS_API_SUCCEED";
export const CHANGE_PASS_API_FAIL = "CHANGE_PASS_API_FAIL";

export const GET_FINANCIAL_API = "GET_FINANCIAL_API";
export const GET_FINANCIAL_API_SUCCEED = "GET_FINANCIAL_API_SUCCEED";
export const GET_FINANCIAL_API_FAIL = "GET_FINANCIAL_API_FAIL";

export const GET_LIST_REGISTRATION_API = "GET_LIST_REGISTRATION_API";
export const GET_LIST_REGISTRATION_API_SUCCEED =
  "GET_LIST_REGISTRATION_API_SUCCEED";
export const GET_LIST_REGISTRATION_API_FAIL = "GET_LIST_REGISTRATION_API_FAIL";

export const GET_DETAILED_REGISTRATION_API = "GET_DETAILED_REGISTRATION_API";
export const GET_DETAILED_REGISTRATION_API_SUCCEED =
  "GET_DETAILED_REGISTRATION_API_SUCCEED";
export const GET_DETAILED_REGISTRATION_API_FAIL =
  "GET_DETAILED_REGISTRATION_API_FAIL";

export const ACCEPT_REGISTRATION_API = "ACCEPT_REGISTRATION_API";
export const ACCEPT_REGISTRATION_API_SUCCEED =
  "ACCEPT_REGISTRATION_API_SUCCEED";
export const ACCEPT_REGISTRATION_API_FAIL = "ACCEPT_REGISTRATION_API_FAIL";

export const DENY_REGISTRATION_API = "DENY_REGISTRATION_API";
export const DENY_REGISTRATION_API_SUCCEED = "DENY_REGISTRATION_API_SUCCEED";
export const DENY_REGISTRATION_API_FAIL = "DENY_REGISTRATION_API_FAIL";

export const GET_NOTIFICATIONS_API = "GET_NOTIFICATIONS_API";
export const GET_NOTIFICATIONS_API_SUCCEED = "GET_NOTIFICATIONS_API_SUCCEED";
export const GET_NOTIFICATIONS_API_FAIL = "GET_NOTIFICATIONS_API_FAIL";

export const GET_DETAILED_NOTIFICATION_API = "GET_DETAILED_NOTIFICATION_API";
export const GET_DETAILED_NOTIFICATION_API_SUCCEED =
  "GET_DETAILED_NOTIFICATION_API_SUCCEED";
export const GET_DETAILED_NOTIFICATION_API_FAIL =
  "GET_DETAILED_NOTIFICATION_API_FAIL";

export const UPDATE_NOTIFICATION_API = "UPDATE_NOTIFICATION_API";
export const UPDATE_NOTIFICATION_API_SUCCEED =
  "UPDATE_NOTIFICATION_API_SUCCEED";
export const UPDATE_NOTIFICATION_API_FAIL = "UPDATE_NOTIFICATION_API_FAIL";

export const CREATE_NOTIFICATION_API = "CREATE_NOTIFICATION_API";
export const CREATE_NOTIFICATION_API_SUCCEED =
  "CREATE_NOTIFICATION_API_SUCCEED";
export const CREATE_NOTIFICATION_API_FAIL = "CREATE_NOTIFICATION_API_FAIL";

export const DELETE_NOTIFICATION_API = "DELETE_NOTIFICATION_API";
export const DELETE_NOTIFICATION_API_SUCCEED =
  "DELETE_NOTIFICATION_API_SUCCEED";
export const DELETE_NOTIFICATION_API_FAIL = "DELETE_NOTIFICATION_API_FAIL";

export const ADD_DAILY_SCHEDULE_API = "ADD_DAILY_SCHEDULE_API";
export const ADD_DAILY_SCHEDULE_API_SUCCEED = "ADD_DAILY_SCHEDULE_API_SUCCEED";
export const ADD_DAILY_SCHEDULE_API_FAIL = "ADD_DAILY_SCHEDULE_API_FAIL";

export const GET_WATER_ELECTRICAL_UNIT_PRICE_API =
  "GET_WATER_ELECTRICAL_UNIT_PRICE_API";
export const GET_WATER_ELECTRICAL_UNIT_PRICE_API_SUCCEED =
  "GET_WATER_ELECTRICAL_UNIT_PRICE_API_SUCCEED";
export const GET_WATER_ELECTRICAL_UNIT_PRICE_API_FAIL =
  "GET_WATER_ELECTRICAL_UNIT_PRICE_API_FAIL";

export const CREATE_WATER_ELECTRICAL_INDEX_API =
  "CREATE_WATER_ELECTRICAL_INDEX_API";
export const CREATE_WATER_ELECTRICAL_INDEX_API_SUCCEED =
  "CREATE_WATER_ELECTRICAL_INDEX_API_SUCCEED";
export const CREATE_WATER_ELECTRICAL_INDEX_API_FAIL =
  "CREATE_WATER_ELECTRICAL_INDEX_API_FAIL";

export const GET_LIST_WATER_ELECTRICAL_BILL_API =
  "GET_LIST_WATER_ELECTRICAL_BILL_API";
export const GET_LIST_WATER_ELECTRICAL_BILL_API_SUCCEED =
  "GET_LIST_WATER_ELECTRICAL_BILL_API_SUCCEED";
export const GET_LIST_WATER_ELECTRICAL_BILL_API_FAIL =
  "GET_LIST_WATER_ELECTRICAL_BILL_API_FAIL";

export const GET_DETAILED_WATER_ELECTRICAL_BILL_API =
  "GET_DETAILED_WATER_ELECTRICAL_BILL_API";
export const GET_DETAILED_WATER_ELECTRICAL_BILL_API_SUCCEED =
  "GET_DETAILED_WATER_ELECTRICAL_BILL_API_SUCCEED";
export const GET_DETAILED_WATER_ELECTRICAL_BILL_API_FAIL =
  "GET_DETAILED_WATER_ELECTRICAL_BILL_API_FAIL";

export const UPDATE_WATER_ELECTRICAL_BILL_API =
  "UPDATE_WATER_ELECTRICAL_BILL_API";
export const UPDATE_WATER_ELECTRICAL_BILL_API_SUCCEED =
  "UPDATE_WATER_ELECTRICAL_BILL_API_SUCCEED";
export const UPDATE_WATER_ELECTRICAL_BILL_API_FAIL =
  "UPDATE_WATER_ELECTRICAL_BILL_API_FAIL";

export const DELETE_WATER_ELECTRICAL_BILL_API =
  "DELETE_WATER_ELECTRICAL_BILL_API";
export const DELETE_WATER_ELECTRICAL_BILL_API_SUCCEED =
  "DELETE_WATER_ELECTRICAL_BILL_API_SUCCEED";
export const DELETE_WATER_ELECTRICAL_BILL_API_FAIL =
  "DELETE_WATER_ELECTRICAL_BILL_API_FAIL";

export const GET_LIST_WATER_ELECTRICAL_INDEX_API =
  "GET_LIST_WATER_ELECTRICAL_INDEX_API";
export const GET_LIST_WATER_ELECTRICAL_INDEX_API_SUCCEED =
  "GET_LIST_WATER_ELECTRICAL_INDEX_API_SUCCEED";
export const GET_LIST_WATER_ELECTRICAL_INDEX_API_FAIL =
  "GET_LIST_WATER_ELECTRICAL_INDEX_API_FAIL";

export const GET_DETAILED_WATER_ELECTRICAL_INDEX_API =
  "GET_DETAILED_WATER_ELECTRICAL_INDEX_API";
export const GET_DETAILED_WATER_ELECTRICAL_INDEX_API_SUCCEED =
  "GET_DETAILED_WATER_ELECTRICAL_INDEX_API_SUCCEED";
export const GET_DETAILED_WATER_ELECTRICAL_INDEX_API_FAIL =
  "GET_DETAILED_WATER_ELECTRICAL_INDEX_API_FAIL";

export const UPDATE_WATER_ELECTRICAL_INDEX_API =
  "UPDATE_WATER_ELECTRICAL_INDEX_API";
export const UPDATE_WATER_ELECTRICAL_INDEX_API_SUCCEED =
  "UPDATE_WATER_ELECTRICAL_INDEX_API_SUCCEED";
export const UPDATE_WATER_ELECTRICAL_INDEX_API_FAIL =
  "UPDATE_WATER_ELECTRICAL_INDEX_API_FAIL";

export const DELETE_WATER_ELECTRICAL_INDEX_API =
  "DELETE_WATER_ELECTRICAL_INDEX_API";
export const DELETE_WATER_ELECTRICAL_INDEX_API_SUCCEED =
  "DELETE_WATER_ELECTRICAL_INDEX_API_SUCCEED";
export const DELETE_WATER_ELECTRICAL_INDEX_API_FAIL =
  "DELETE_WATER_ELECTRICAL_INDEX_API_FAIL";

export const GET_ROOMS_API = "GET_ROOMS_API";
export const GET_ROOMS_API_SUCCEED = "GET_ROOMS_API_SUCCEED";
export const GET_ROOMS_API_FAIL = "GET_ROOMS_API_FAIL";

export const GET_ROOM_DETAILS_API = "GET_ROOM_DETAILS_API";
export const GET_ROOM_DETAILS_API_SUCCEED = "GET_ROOM_DETAILS_API_SUCCEED";
export const GET_ROOM_DETAILS_API_FAIL = "GET_ROOM_DETAILS_API_FAIL";

export const GET_USED_ROOM_API = "GET_USED_ROOM_API";
export const GET_USED_ROOM_API_SUCCEED = "GET_USED_ROOM_API_SUCCEED";
export const GET_USED_ROOM_API_FAIL = "GET_USED_ROOM_API_FAIL";

export const GET_STATISTICAL_BILL_API = "GET_STATISTICAL_BILL_API";
export const GET_STATISTICAL_BILL_API_SUCCEED =
  "GET_STATISTICAL_BILL_API_SUCCEED";
export const GET_STATISTICAL_BILL_API_FAIL = "GET_STATISTICAL_BILL_API_FAIL";

export const GET_SCHEDULE_API = "GET_SCHEDULE_API";
export const GET_SCHEDULE_API_SUCCEED = "GET_SCHEDULE_API_SUCCEED";
export const GET_SCHEDULE_API_FAIL = "GET_SCHEDULE_FAIL";

export const GET_LIST_EMPLOYEE_API = "GET_LIST_EMPLOYEE_API";
export const GET_LIST_EMPLOYEE_API_SUCCEED = "GET_LIST_EMPLOYEE_API_SUCCEED";
export const GET_LIST_EMPLOYEE_API_FAIL = "GET_LIST_EMPLOYEE_FAIL";

export const GET_EXPENSES_API = "GET_EXPENSES_API";
export const GET_EXPENSES_API_SUCCEED = "GET_EXPENSES_API_SUCCEED";
export const GET_EXPENSES_API_FAIL = "GET_EXPENSES_FAIL";

export const DELETE_STUDENT_IN_ROOM_API = "DELETE_STUDENT_IN_ROOM_API";
export const DELETE_STUDENT_IN_ROOM_API_SUCCEED =
  "DELETE_STUDENT_IN_ROOM_API_SUCCEED";
export const DELETE_STUDENT_IN_ROOM_API_FAIL = "DELETE_STUDENT_IN_ROOM_FAIL";

export const FETCH_NAV_USER = "FETCH_NAV_USER";

export const POST_UPDATE_MY_PROFILE_API = "POST_UPDATE_MY_PROFILE_API";
export const POST_UPDATE_MY_PROFILE_API_SUCCEED =
  "POST_UPDATE_MY_PROFILE_API_SUCCEED";
export const POST_UPDATE_MY_PROFILE_API_FAIL = "POST_UPDATE_MY_PROFILE_FAIL";

export const GET_REVENUES_API = "GET_REVENUES_API";
export const GET_REVENUES_API_SUCCEED = "GET_REVENUES_API_SUCCEED";
export const GET_REVENUES_API_FAIL = "GET_REVENUES_FAIL";

export const GET_ACCOUNTS_API = "GET_ACCOUNTS_API";
export const GET_ACCOUNTS_API_SUCCEED = "GET_ACCOUNTS_API_SUCCEED";
export const GET_ACCOUNTS_API_FAIL = "GET_ACCOUNTS_FAIL";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT_API";
export const CREATE_ACCOUNT_API_SUCCEED = "CREATE_ACCOUNT_API_SUCCEED";
export const CREATE_ACCOUNT_API_FAIL = "CREATE_ACCOUNT_FAIL";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT_API";
export const UPDATE_ACCOUNT_API_SUCCEED = "UPDATE_ACCOUNT_API_SUCCEED";
export const UPDATE_ACCOUNT_API_FAIL = "UPDATE_ACCOUNT_FAIL";

export const GET_GROUP_AND_PERMISSION_API = "GET_GROUP_AND_PERMISSION_API";
export const GET_GROUP_AND_PERMISSION_API_SUCCEED =
  "GET_GROUP_AND_PERMISSION_API_SUCCEED";
export const GET_GROUP_AND_PERMISSION_API_FAIL =
  "GET_GROUP_AND_PERMISSION_FAIL";

export const GET_FACULTY_API = "GET_FACULTY_API";
export const GET_FACULTY_API_SUCCEED = "GET_FACULTY_API_SUCCEED";
export const GET_FACULTY_API_FAIL = "GET_FACULTY_API_FAIL";

export const GET_CLASS_API = "GET_CLASS_API";
export const GET_CLASS_API_SUCCEED = "GET_CLASS_API_SUCCEED";
export const GET_CLASS_API_FAIL = "GET_CLASS_API_FAIL";

export const GET_POSITION_API = "GET_POSITION_API";
export const GET_POSITION_API_SUCCEED = "GET_POSITION_API_SUCCEED";
export const GET_POSITION_API_FAIL = "GET_POSITION_API_FAIL";

export const GET_AREA_API = "GET_AREA_API";
export const GET_AREA_API_SUCCEED = "GET_AREA_API_SUCCEED";
export const GET_AREA_API_FAIL = "GET_AREA_API_FAIL";

export const GET_CONTRACTS_API = "GET_CONTRACTS_API";
export const GET_CONTRACTS_API_SUCCEED = "GET_CONTRACTS_API_SUCCEED";
export const GET_CONTRACTS_API_FAIL = "GET_CONTRACTS_FAIL";

export const GET_DETAILED_CONTRACT_API = "GET_DETAILED_CONTRACT_API";
export const GET_DETAILED_CONTRACT_API_SUCCEED =
  "GET_DETAILED_CONTRACT_API_SUCCEED";
export const GET_DETAILED_CONTRACT_API_FAIL = "GET_DETAILED_CONTRACT_FAIL";

export const GET_DETAILED_ACCOUNT_API = "GET_DETAILED_ACCOUNT_API";
export const GET_DETAILED_ACCOUNT_API_SUCCEED =
  "GET_DETAILED_ACCOUNT_API_SUCCEED";
export const GET_DETAILED_ACCOUNT_API_FAIL = "GET_DETAILED_ACCOUNT_FAIL";
