export const actionType = {
    /*..Login....*/
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    /*..Change_password..*/
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAIL: 'CHANGE_PASSWORD_FAIL',
    /*..Change_info..*/
    CHANGE_INFO: 'CHANGE_INFO',
    CHANGE_INFO_SUCCESSL: 'CHANGE_INFO_SUCCESSL',
    CHANGE_INFO_FAIL: 'CHANGE_INFO_FAIL',
    /*..Get_calendar_staff..*/
    GET_CALENDAR_STAFF: 'GET_CALENDAR_STAFF',
    GET_CALENDAR_STAFF_SUCCESS: 'GET_CALENDAR_STAFF_SUCCESS',
    GET_CALENDAR_STAFF_FAIL: 'GET_CALENDAR_STAFF_FAIL',
  };
  