export const actionType = {
    /*..Login....*/
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    /*..Change_password..*/
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAIL: 'CHANGE_PASSWORD_FAIL',
    /*..Change_info..*/
    CHANGE_INFO: 'CHANGE_INFO',
    CHANGE_INFO_SUCCESSL: 'CHANGE_INFO_SUCCESSL',
    CHANGE_INFO_FAIL: 'CHANGE_INFO_FAIL',
    /*..Get_profile..*/
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
    /*..Get_calendar_staff..*/
    GET_CALENDAR_STAFF: 'GET_CALENDAR_STAFF',
    GET_CALENDAR_STAFF_SUCCESS: 'GET_CALENDAR_STAFF_SUCCESS',
    GET_CALENDAR_STAFF_FAIL: 'GET_CALENDAR_STAFF_FAIL',
    /*..Get_all_room..*/
    GET_ALL_ROOM: 'GET_ALL_ROOM',
    GET_ALL_ROOM_SUCCESS: 'GET_ALL_ROOM_SUCCESS',
    GET_ALL_ROOM_FAIL: 'GET_ALL_ROOM_FAIL',
    /*..Search_room..*/
    SEARCH_ROOM: 'SEARCH_ROOM',
    SEARCH_ROOM_SUCCESS: 'SEARCH_ROOM_SUCCESS',
    SEARCH_ROOM_FAIL: 'SEARCH_ROOM_FAIL',
    /*..Main_menu..*/
    STATUS_MAIN_MENU: 'STATUS_MAIN_MENU',
    /*..Get_all_student..*/
    GET_ALL_STUDENT: 'GET_ALL_STUDENT',
    GET_ALL_STUDENT_SUCCESS: 'GET_ALL_STUDENT_SUCCESS',
    GET_ALL_STUDENT_FAIL: 'GET_ALL_STUDENT_FAIL',
    /*..Background_color..*/
    COLOR: 'COLOR',
    /*..Get_area..*/
    GET_AREA_SUCCESS: 'GET_AREA_SUCCESS',
    GET_AREA_FAIL: 'GET_AREA_FAIL',
    /*..Get_class..*/
    GET_CLASS_SUCCESS: 'GET_CLASS_SUCCESS',
    GET_CLASS_FAIL: 'GET_CLASS_FAIL',
    /*..Get_position..*/
    GET_POSITION_SUCCESS: 'GET_POSITION_SUCCESS',
    GET_POSITION_FAIL: 'GET_POSITION_FAIL',
    /*..Get_faculti..*/
    GET_FACULTI_SUCCESS: 'GET_FACULTI_SUCCESS',
    GET_FACULTI_FAIL: 'GET_FACULTI_FAIL',
    /*..Get_faculti..*/
    GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
    GET_NOTIFICATION_FAIL: 'GET_NOTIFICATION_FAIL',
  };
  