export const apiUrl = {
  LOGIN_URL: 'https://dutdormitory.tk/api/auth/login/',
  CHANGE_PASSWORD_URL: 'https://dutdormitory.tk/api/account/change-password/',
  CHANGE_PROFILE_URL: 'https://dutdormitory.tk/api/account/update-user-profile/',
  FORGOT_PASSWORD_URL: 'https://dutdormitory.tk/api/auth/forgot-password/',
  GET_CALENDAR_STAFF_URL: 'https://dutdormitory.tk/api/daily-schedules/',
  PROFILE_URL: 'https://dutdormitory.tk/api/account/get-user-profile/',
  GET_ALL_STUDENT_URL: 'https://dutdormitory.tk/api/students/get-all-student/',
  GET_ALL_STAFF_URL: 'https://dutdormitory.tk/api/staffs/get-all-staff/',
  GET_AREA: 'https://dutdormitory.tk/api/area/',
  GET_FACULTI: 'https://dutdormitory.tk/api/faculty/',
  GET_POSITION: 'https://dutdormitory.tk/api/position/',
  GET_CLASS: 'https://dutdormitory.tk/api/class/',
  NOTIFICATION_URL: 'https://dutdormitory.tk/api/notifications/',
  GET_ALL_ROOM_URL: 'https://dutdormitory.tk/api/rooms/get-all/',
  REGISTRATION_ROOM_URL: 'https://dutdormitory.tk/api/contracts/',
  GET_DASHBOARD_URL: 'https://dutdormitory.tk/api/dashboard/',
  GET_PAYMENT_METHOD_URL: 'https://dutdormitory.tk/api/payment-method/',
  GET_DETAIL_ROOM_URL: 'https://dutdormitory.tk/api/rooms/',
};
