export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const FETCH_NAV_TITLE = "FETCH_NAV_TITLE";

export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE_API = "GET_PROFILE_API";
export const GET_PROFILE_API_SUCCEED = "GET_PROFILE_API_SUCCEED";
export const GET_PROFILE_API_FAIL = "GET_PROFILE_API_FAIL";

export const CHANGE_PASS_API = "CHANGE_PASS_API";
export const CHANGE_PASS_API_SUCCEED = "CHANGE_PASS_API_SUCCEED";
export const CHANGE_PASS_API_FAIL = "CHANGE_PASS_API_FAIL";

export const GET_ROOMS_API = "GET_ROOMS_API";
export const GET_ROOMS_API_SUCCEED = "GET_ROOMS_API_SUCCEED";
export const GET_ROOMS_API_FAIL = "GET_ROOMS_API_FAIL";

export const GET_FACULTIES_API = "GET_FACULTIES_API";
export const GET_FACULATIES_API_SUCCEED = "GET_FACULTIES_API_SUCCEED";
export const GET_FACULATIE_API_FAIL = "GET_FACULTIES_API_FAIL";

export const GET_GRADE_API = "GET_GRADE_API";
export const GET_GRADE_API_SUCCEED = "GET_GRADE_API_SUCCEED";
export const GET_GRADE_API_FAIL = "GET_GRADE_API_FAIL";

export const GET_EMPLOYEES_API = "GET_EMPLOYEES_API";
export const GET_EMPLOYEES_API_SUCCEED = "GET_EMPLOYEES_API_SUCCEED";
export const GET_EMPLOYEES_API_FAIL = "GET_EMPLOYEES_API_FAIL";

export const GET_STUDENTS_API = "GET_STUDENTS_API";
export const GET_STUDENTS_API_SUCCEED = "GET_STUDENTS_API_SUCCEED";
export const GET_STUDENTS_API_FAIL = "GET_STUDENTS_API_FAIL";

export const GET_ROOM_DETAILS_API = "GET_ROOM_DETAILS_API";
export const GET_ROOM_DETAILS_API_SUCCEED = "GET_ROOM_DETAILS_API_SUCCEED";
export const GET_ROOM_DETAILS_API_FAIL = "GET_STUDENTS_API_FAIL";


