export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";
export const FETCH_NAV_TITLE = "FETCH_NAV_TITLE";
export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ROOMS_LIST = "GET_ROOMS_LIST";
