export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const FETCH_NAV_TITLE = "FETCH_NAV_TITLE";

export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE_API = "GET_PROFILE_API";
export const GET_PROFILE_API_SUCCEED = "GET_PROFILE_API_SUCCEED";
export const GET_PROFILE_API_FAIL = "GET_PROFILE_API_FAIL";

export const CHANGE_PASS_API = "CHANGE_PASS_API";
export const CHANGE_PASS_API_SUCCEED = "CHANGE_PASS_API_SUCCEED";
export const CHANGE_PASS_API_FAIL = "CHANGE_PASS_API_FAIL";

export const GET_ROOMS_API = "GET_ROOMS_API";
export const GET_ROOMS_API_SUCCEED = "GET_ROOMS_API_SUCCEED";
export const GET_ROOMS_API_FAIL = "GET_ROOMS_API_FAIL";

export const GET_FACULTIES_API = "GET_FACULTIES_API";
export const GET_FACULATIES_API_SUCCEED = "GET_FACULTIES_API_SUCCEED";
export const GET_FACULATIE_API_FAIL = "GET_FACULTIES_API_FAIL";

export const GET_GRADE_API = "GET_GRADE_API";
export const GET_GRADE_API_SUCCEED = "GET_GRADE_API_SUCCEED";
export const GET_GRADE_API_FAIL = "GET_GRADE_API_FAIL";

export const GET_EMPLOYEES_API = "GET_EMPLOYEES_API";
export const GET_EMPLOYEES_API_SUCCEED = "GET_EMPLOYEES_API_SUCCEED";
export const GET_EMPLOYEES_API_FAIL = "GET_EMPLOYEES_API_FAIL";

export const GET_STUDENTS_API = "GET_STUDENTS_API";
export const GET_STUDENTS_API_SUCCEED = "GET_STUDENTS_API_SUCCEED";
export const GET_STUDENTS_API_FAIL = "GET_STUDENTS_API_FAIL";

export const GET_ROOM_DETAILS_API = "GET_ROOM_DETAILS_API";
export const GET_ROOM_DETAILS_API_SUCCEED = "GET_ROOM_DETAILS_API_SUCCEED";
export const GET_ROOM_DETAILS_API_FAIL = "GET_ROOM_DETAILS_API_FAIL";

export const GET_DETAILED_STUDENT_API = "GET_DETAILED_STUDENT_API";
export const GET_DETAILED_STUDENT_API_SUCCEED =
  "GET_DETAILED_STUDENT_API_SUCCEED";
export const GET_DETAILED_STUDENT_API_FAIL = "GET_DETAILED_STUDENT_FAIL";

export const GET_DETAILED_EMPLOYEE_API = "GET_DETAILED_EMPLOYEE_API";
export const GET_DETAILED_EMPLOYEE_API_SUCCEED =
  "GET_DETAILED_EMPLOYEE_API_SUCCEED";
export const GET_DETAILED_EMPLOYEE_API_FAIL = "GET_DETAILED_EMPLOYEE_FAIL";

export const GET_PAYMENT_METHODS_API = "GET_PAYMENT_METHODS_API";
export const GET_PAYMENT_METHODS_API_SUCCEED =
  "GET_PAYMENT_METHODS_API_SUCCEED";
export const GET_PAYMENT_METHODS_API_FAIL = "GET_PAYMENT_METHODS_FAIL";

export const POST_REGISTRATION_API = "POST_REGISTRATION_API";
export const POST_REGISTRATION_API_SUCCEED = "POST_REGISTRATION_API_SUCCEED";
export const POST_REGISTRATION_API_FAIL = "POST_REGISTRATION_FAIL";

export const GET_MY_SCHEDULE_API = "GET_MY_SCHEDULE_API";
export const GET_MY_SCHEDULE_API_SUCCEED = "GET_MY_SCHEDULE_API_SUCCEED";
export const GET_MY_SCHEDULE_API_FAIL = "GET_MY_SCHEDULE_FAIL";

export const POST_UPDATE_MY_PROFILE_API = "POST_UPDATE_MY_PROFILE_API";
export const POST_UPDATE_MY_PROFILE_API_SUCCEED =
  "POST_UPDATE_MY_PROFILE_API_SUCCEED";
export const POST_UPDATE_MY_PROFILE_API_FAIL = "POST_UPDATE_MY_PROFILE_FAIL";

export const GET_NOTIFICATIONS_API = "GET_NOTIFICATIONS_API";
export const GET_NOTIFICATIONS_API_SUCCEED = "GET_NOTIFICATIONS_API_SUCCEED";
export const GET_NOTIFICATIONS_API_FAIL = "GET_NOTIFICATIONS_FAIL";

export const GET_DASHBOARD_API = "GET_DASHBOARD_API";
export const GET_DASHBOARD_API_SUCCEED = "GET_DASHBOARD_API_SUCCEED";
export const GET_DASHBOARD_API_FAIL = "GET_DASHBOARD_FAIL";

export const FETCH_NAV_USER = "FETCH_NAV_USER";

export const SEND_EMAIL_API = "SEND_EMAIL_API";
export const SEND_EMAIL_API_SUCCEED = "SEND_EMAIL_API_SUCCEED";
export const SEND_EMAIL_API_FAIL = "SEND_EMAIL_FAIL";